[package]
name = "continuation"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic-waker = "*"
thiserror = "*"
[dev-dependencies]
truntime = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/truntime.git"}